### ISSUE TITLE
PRACTICA OPERACIONES DE SISTEMAS NUMERICOS

### ISSUE THREAD

**Issue by LeinnaMora** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-LeinnaMora#1]
[practica_matematicasDiscretas.pdf](https://github.com/user-attachments/files/16832554/practica_matematicasDiscretas.pdf)

**Comment by Ivan-PerezZ** [comment]
portada: 22
Procedimiento: 23
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la práctica: 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
